<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../../assets/recap-brun.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../TheEnd.Core/TheEnd.Core.csproj" /></ItemGroup>
  <ItemGroup>
    <Resource Include="../../assets/recap-brun-icon-transparent.png" Link="assets/recap-brun-icon-transparent.png" />
    <Resource Include="../../assets/recap-brun.ico" Link="assets/recap-brun.ico" />
  </ItemGroup>
</Project>
